### ISSUE TITLE
libimxvpuapi freezes with normal h264 decoding

### ISSUE THREAD

**Issue by ttykkala** [Freescale/libimxvpuapi#11]
I tested example/decode-example with given h264 test file (test-320x240.h264)
and it seems to run but on third execuction time it fails. 

Here's the log:
//////////////////////////////////////////////////////////
/imxvpuapi/imxvpuapi_vpulib.c:1807 (imx_vpu_dec_decode)   log: input info: 6214 byte
 ../imxvpuapi/imxvpuapi_vpulib.c:1846 (imx_vpu_dec_decode)   log: pushing main frame data with 6214 byte
../imxvpuapi/imxvpuapi_vpulib.c:1691 (imx_vpu_dec_push_input_data)   log: bitstream buffer status:  read ptr 0x44c37090  write ptr 0x44c37093  num free bytes 3143676
../imxvpuapi/imxvpuapi_vpulib.c:2063 (imx_vpu_dec_decode)   log: waiting for decoding completion
../imxvpuapi/imxvpuapi_vpulib.c:2072 (imx_vpu_dec_decode)   info: timeout after waiting 500 ms for frame completion
../imxvpuapi/imxvpuapi_vpulib.c:2072 (imx_vpu_dec_decode)   info: timeout after waiting 500 ms for frame completion
../imxvpuapi/imxvpuapi_vpulib.c:2072 (imx_vpu_dec_decode)   info: timeout after waiting 500 ms for frame completion
../imxvpuapi/imxvpuapi_vpulib.c:2072 (imx_vpu_dec_decode)   info: timeout after waiting 500 ms for frame completion
[ERR] fatal: VPU is busy in vpu_DecGetOutputInfo
imx_vpu_dec_decode() failed: timeout
../imxvpuapi/imxvpuapi_vpulib.c:1104 (imx_vpu_dec_close)   debug: closing decoder
////////////////////////////////////////////////////////////

Should the provided example work normally with any number of execution times?
My goal is to decode h264 video on VPU.

The best,
Tommi

**Comment by dv1** [comment]
Yes, this should work no matter how often it is executed. Check out https://github.com/Freescale/gstreamer-imx/blob/master/docs/faq.md#vpu-operation-freezes-and-vpu-blocking-timeout-messages-appear . Also let me know your platform, your kernel version, and your imx-vpu version.

**Comment by ttykkala** [comment]
Kernel version is 4.1.15:

Linux 10:0d:32:01:7e:d1 4.1.15-224156-g141e464 #3 SMP PREEMPT Thu Apr 21 11:34:38 EEST 2016 armv7l GNU/Linux

Its a custom platform, Freescale NXP IMX6 Yocto 2.0 Release 
vpu firmware: 3.1, release 1, lib 5.4, librelease: 33

I have  CONFIG_MX6_VPU_352M kernel parameter set On because last time I checked
it got stuck being off too.

The best,
Tommi

**Comment by ttykkala** [comment]
We found the reason for this timeout problem.

Seems to be due to our kernel configuration:
CONFIG_IMX_IPUV3_CORE flag seems to cause
problems for VPU decoding.

-T

**Comment by dv1** [comment]
Thanks! I added some notes about the VPU timeouts, and included your finding. Closing this now. Please reopen if you still have problems with the VPU.

**Comment by ttykkala** [comment]
Hi,

Additional info related to this problem.

The final real reason behind VPU timeouts was wrong input voltage
to SMARC processor card. After changing from 3.3V -> 5V 
timeout problems disappeared.

-T

**Comment by dv1** [comment]
Excellent, thanks. Will add that to the documentation.

**Comment by ttykkala** [comment]
After even further debugging it was finally a device tree patch which fixed this issue:


diff --git a/arch/arm/boot/dts/imx6dl-smarcfimx6.dts b/arch/arm/boot/dts/imx6dl-smarcfimx6.dts
index 3e121d6..56fb08a 100644
--- a/arch/arm/boot/dts/imx6dl-smarcfimx6.dts
+++ b/arch/arm/boot/dts/imx6dl-smarcfimx6.dts
@@ -72,7 +72,3 @@
 &pxp {
 	status = "okay";
 };
-
-&vpu {
-    pu-supply = <&reg_pu>; /* ldo-bypass:use pu_dummy if VDDSOC share with VDDPU */
-};
diff --git a/arch/arm/boot/dts/imx6q-smarcfimx6.dts b/arch/arm/boot/dts/imx6q-smarcfimx6.dts
index 4732e0c..6a0e4a5 100644
--- a/arch/arm/boot/dts/imx6q-smarcfimx6.dts
+++ b/arch/arm/boot/dts/imx6q-smarcfimx6.dts
@@ -55,7 +55,3 @@
 &sata {
 	status = "okay";
 };
-
-&vpu {
-    pu-supply = <&reg_pu>; /* ldo-bypass:use pu_dummy if VDDSOC share with VDDPU */
-};
diff --git a/arch/arm/boot/dts/imx6qdl-smarcfimx6.dtsi b/arch/arm/boot/dts/imx6qdl-smarcfimx6.dtsi
index 33f24f9..725fb5c 100644
--- a/arch/arm/boot/dts/imx6qdl-smarcfimx6.dtsi
+++ b/arch/arm/boot/dts/imx6qdl-smarcfimx6.dtsi
@@ -80,17 +80,6 @@
                         regulator-max-microvolt = <3300000>;
                         regulator-always-on;
                 };
-
-		reg_sensor: regulator@4 {
-			compatible = "regulator-fixed";
-			reg = <4>;
-			regulator-name = "sensor-supply";
-			regulator-min-microvolt = <3300000>;
-			regulator-max-microvolt = <3300000>;
-			gpio = <&gpio2 31 0>;
-			startup-delay-us = <500>;
-			enable-active-high;
-		};
 	};
 
         sound-sgtl5000 {
@@ -211,7 +200,8 @@
 };
 
 &cpu0 {
-        pu-supply = <&reg_pu>; /* ldo-bypass:use pu_dummy if VDDSOC share with VDDPU */
+        arm-supply = <&reg_arm>;
+        soc-supply = <&reg_soc>;
 };
 
 &ecspi1 {
@@ -283,18 +273,18 @@
 
 &fec {
 	pinctrl-names = "default";
-        pinctrl-0 = <&pinctrl_enet>, <&pinctrl_enet_irq>;
+        pinctrl-0 = <&pinctrl_enet>;
 	phy-mode = "rgmii";
-	fsl,magic-packet;
+        interrupts = <&pinctrl_enet_irq>;
+	/*fsl,magic-packet;*/
 	status = "okay";
 };
 
 &gpc {
         /* use ldo-enable, u-boot will check it and configure */
-        fsl,ldo-bypass = <1>;
+        fsl,ldo-bypass = <0>;
         /* watchdog select of reset source */
         fsl,wdog-reset = <1>;
-        pu-supply = <&reg_pu>; /* ldo-bypass:use pu_dummy if VDDSOC share with VDDPU */
 };
 
 &dcic1 {
@@ -356,6 +346,8 @@
         s35390a: s35390a@30 {
                 compatible = "s35390a";
                 reg = <0x30>;
+		interrupt-parent = <&gpio3>;
+		interrupts = <30 0>, <31 0>;
         };
 
         cape_eeprom0: cape_eeprom@57 {
@@ -470,8 +462,8 @@
 				MX6QDL_PAD_EIM_D29__GPIO3_IO29          0x80000000
                                 MX6QDL_PAD_GPIO_2__GPIO1_IO02           0x80000000
                                 MX6QDL_PAD_SD1_CMD__GPIO1_IO18          0x80000000
-                                MX6QDL_PAD_EIM_D30__GPIO3_IO30          0x410
-                                MX6QDL_PAD_EIM_D31__GPIO3_IO31          0x410
+                                /*MX6QDL_PAD_EIM_D30__GPIO3_IO30          0x410
+                                MX6QDL_PAD_EIM_D31__GPIO3_IO31          0x410*/
                                 MX6QDL_PAD_DI0_PIN4__GPIO4_IO20         0x80000000
                                 MX6QDL_PAD_CSI0_MCLK__CCM_CLKO1         0x130b0
 			>;
@@ -896,7 +888,7 @@
 	pinctrl-names = "default";
 	pinctrl-0 = <&pinctrl_usdhc3>;
 	bus-width = <8>;
-	cd-gpios = <&gpio2 0 GPIO_ACTIVE_LOW>;
+	cd-gpios = <&gpio6 10 GPIO_ACTIVE_LOW>;
 	wp-gpios = <&gpio2 1 GPIO_ACTIVE_HIGH>;
 	no-1-8-v;
 	keep-power-in-suspend;

**Comment by ttykkala** [comment]
After even further debugging it was finally a device tree patch which fixed this issue:

`diff --git a/arch/arm/boot/dts/imx6dl-smarcfimx6.dts b/arch/arm/boot/dts/imx6dl-smarcfimx6.dts
index 3e121d6..56fb08a 100644
--- a/arch/arm/boot/dts/imx6dl-smarcfimx6.dts
+++ b/arch/arm/boot/dts/imx6dl-smarcfimx6.dts
@@ -72,7 +72,3 @@
 &pxp {
 	status = "okay";
 };
-
-&vpu {
-    pu-supply = <&reg_pu>; /* ldo-bypass:use pu_dummy if VDDSOC share with VDDPU */
-};
diff --git a/arch/arm/boot/dts/imx6q-smarcfimx6.dts b/arch/arm/boot/dts/imx6q-smarcfimx6.dts
index 4732e0c..6a0e4a5 100644
--- a/arch/arm/boot/dts/imx6q-smarcfimx6.dts
+++ b/arch/arm/boot/dts/imx6q-smarcfimx6.dts
@@ -55,7 +55,3 @@
 &sata {
 	status = "okay";
 };
-
-&vpu {
-    pu-supply = <&reg_pu>; /* ldo-bypass:use pu_dummy if VDDSOC share with VDDPU */
-};
diff --git a/arch/arm/boot/dts/imx6qdl-smarcfimx6.dtsi b/arch/arm/boot/dts/imx6qdl-smarcfimx6.dtsi
index 33f24f9..725fb5c 100644
--- a/arch/arm/boot/dts/imx6qdl-smarcfimx6.dtsi
+++ b/arch/arm/boot/dts/imx6qdl-smarcfimx6.dtsi
@@ -80,17 +80,6 @@
                         regulator-max-microvolt = <3300000>;
                         regulator-always-on;
                 };
-
-		reg_sensor: regulator@4 {
-			compatible = "regulator-fixed";
-			reg = <4>;
-			regulator-name = "sensor-supply";
-			regulator-min-microvolt = <3300000>;
-			regulator-max-microvolt = <3300000>;
-			gpio = <&gpio2 31 0>;
-			startup-delay-us = <500>;
-			enable-active-high;
-		};
 	};
 
         sound-sgtl5000 {
@@ -211,7 +200,8 @@
 };
 
 &cpu0 {
-        pu-supply = <&reg_pu>; /* ldo-bypass:use pu_dummy if VDDSOC share with VDDPU */
+        arm-supply = <&reg_arm>;
+        soc-supply = <&reg_soc>;
 };
 
 &ecspi1 {
@@ -283,18 +273,18 @@
 
 &fec {
 	pinctrl-names = "default";
-        pinctrl-0 = <&pinctrl_enet>, <&pinctrl_enet_irq>;
+        pinctrl-0 = <&pinctrl_enet>;
 	phy-mode = "rgmii";
-	fsl,magic-packet;
+        interrupts = <&pinctrl_enet_irq>;
+	/*fsl,magic-packet;*/
 	status = "okay";
 };
 
 &gpc {
         /* use ldo-enable, u-boot will check it and configure */
-        fsl,ldo-bypass = <1>;
+        fsl,ldo-bypass = <0>;
         /* watchdog select of reset source */
         fsl,wdog-reset = <1>;
-        pu-supply = <&reg_pu>; /* ldo-bypass:use pu_dummy if VDDSOC share with VDDPU */
 };
 
 &dcic1 {
@@ -356,6 +346,8 @@
         s35390a: s35390a@30 {
                 compatible = "s35390a";
                 reg = <0x30>;
+		interrupt-parent = <&gpio3>;
+		interrupts = <30 0>, <31 0>;
         };
 
         cape_eeprom0: cape_eeprom@57 {
@@ -470,8 +462,8 @@
 				MX6QDL_PAD_EIM_D29__GPIO3_IO29          0x80000000
                                 MX6QDL_PAD_GPIO_2__GPIO1_IO02           0x80000000
                                 MX6QDL_PAD_SD1_CMD__GPIO1_IO18          0x80000000
-                                MX6QDL_PAD_EIM_D30__GPIO3_IO30          0x410
-                                MX6QDL_PAD_EIM_D31__GPIO3_IO31          0x410
+                                /*MX6QDL_PAD_EIM_D30__GPIO3_IO30          0x410
+                                MX6QDL_PAD_EIM_D31__GPIO3_IO31          0x410*/
                                 MX6QDL_PAD_DI0_PIN4__GPIO4_IO20         0x80000000
                                 MX6QDL_PAD_CSI0_MCLK__CCM_CLKO1         0x130b0
 			>;
@@ -896,7 +888,7 @@
 	pinctrl-names = "default";
 	pinctrl-0 = <&pinctrl_usdhc3>;
 	bus-width = <8>;
-	cd-gpios = <&gpio2 0 GPIO_ACTIVE_LOW>;
+	cd-gpios = <&gpio6 10 GPIO_ACTIVE_LOW>;
 	wp-gpios = <&gpio2 1 GPIO_ACTIVE_HIGH>;
 	no-1-8-v;
 	keep-power-in-suspend;`

**Comment by ttykkala** [comment]
After even further debugging it was finally a device tree patch which fixed this issue,

here's a link to kernel patch:
https://drive.google.com/file/d/0B2jrHa33l-ljSGVmLXMxZ0tONWM/view?usp=sharing

Cheers,
Tommi

**Comment by ttykkala** [comment]
ttykkala commented just now
After even further debugging it was finally a device tree patch which fixed this issue,

here's a link to device tree patch:
https://drive.google.com/file/d/0B2jrHa33l-ljSGVmLXMxZ0tONWM/view?usp=sharing

Cheers,
Tommi

**Comment by ttykkala** [comment]
After even further debugging it was finally a device tree patch which fixed this issue,

here's a link to device tree patch:
https://drive.google.com/file/d/0B2jrHa33l-ljSGVmLXMxZ0tONWM/view?usp=sharing

Cheers,
Tommi
