### ISSUE TITLE
Function imx_vpu_dec_get_initial_info return failed

### ISSUE THREAD

**Issue by sharmer** [Freescale/libimxvpuapi#12]
Hi, 
When I try to use libimxvpuapi for decode H.264 stream, but i get error when call imx_vpu_dec_decode(), I trace into the vpulib code, find seems error happened in below place.
Could you please give some advice on this error. thanks.
RetCode vpu_DecGetInitialInfo(DecHandle handle, DecInitialInfo * info)

		if (pDecInfo->openParam.bitstreamMode && (val & (1 << 4))) {
			VpuWriteReg(BIT_RUN_INDEX, pCodecInst->instIndex);
			UnlockVpu(vpu_semap);
			return RETCODE_FAILURE;
		}
CPU: Freescale i.MX 6Quad/DualLite/Solo
System: Linux
vpu lib version : major.minor.rel=5.4.16 
vpu fw version : major.minor.rel_rcode=2.3.10_r40778 

below is debug output.
imxvpuapi_vpulib.c:1811 (imx_vpu_dec_decode)   log: input info: 161 byte
imxvpuapi_vpulib.c:1850 (imx_vpu_dec_decode)   log: pushing main frame data with 161 byte
imxvpuapi_vpulib.c:1695 (imx_vpu_dec_push_input_data)   log: bitstream buffer status:  read ptr 0x18800000  write ptr 0x18800000  num free bytes 3143679
[DEBUG] vpu_lib.c:3444 enter vpu_DecGetBitstreamBuffer()
[DEBUG] vpu_io.c:716 vpu clock gate setting = 1
[DEBUG] vpu_io.c:716 vpu clock gate setting = 0
imxvpuapi_vpulib.c:1363 (imx_vpu_dec_get_initial_info)   log: i.MX6Q
[DEBUG] vpu_lib.c:3525 enter vpu_DecUpdateBitstreamBuffer()
[DEBUG] vpu_lib.c:3526 Update bitstream buffer size 161
[DEBUG] vpu_io.c:716 vpu clock gate setting = 1
[DEBUG] vpu_io.c:716 vpu clock gate setting = 0
[DEBUG] vpu_lib.c:2748 enter vpu_DecSetEscSeqInit()
[DEBUG] vpu_io.c:716 vpu clock gate setting = 1
[DEBUG] vpu_io.c:716 vpu clock gate setting = 0
imxvpuapi_vpulib.c:1366 (imx_vpu_dec_get_initial_info)   log: i.MX6X
imxvpuapi_vpulib.c:1369 (imx_vpu_dec_get_initial_info)   log: B errorcode: 0
imxvpuapi_vpulib.c:1372 (imx_vpu_dec_get_initial_info)   log: A errorcode: 0
[DEBUG] vpu_lib.c:2794 enter vpu_DecGetInitialInfo()
[DEBUG] vpu_io.c:716 vpu clock gate setting = 1
[DEBUG] vpu_io.c:716 vpu clock gate setting = 1
[DEBUG] vpu_io.c:716 vpu clock gate setting = 0
[DEBUG] vpu_io.c:716 vpu clock gate setting = 1
[DEBUG] vpu_util.c:328 BitIssueCommand 1
[DEBUG] vpu_io.c:716 vpu clock gate setting = 0
[DEBUG] vpu_io.c:716 vpu clock gate setting = 0
imxvpuapi_vpulib.c:1373 (imx_vpu_dec_get_initial_info)   log: dec_ret    : -1
imxvpuapi_vpulib.c:1379 (imx_vpu_dec_get_initial_info)   ERROR: could not retrieve configuration information: failure
[DEBUG] vpu_lib.c:2748 enter vpu_DecSetEscSeqInit()
[DEBUG] vpu_io.c:716 vpu clock gate setting = 1
[DEBUG] vpu_io.c:716 vpu clock gate setting = 0
imxvpuapi_vpulib.c:1936 (imx_vpu_dec_decode)   ERROR: Internal error: unspecified error

**Comment by sharmer** [comment]
OK, I find the reason, vpu didnot support avcc h.264, i need to convert them to annex b.

**Comment by sharmer** [comment]
BTW, libimxvpuapi looks much better than VPU wrapper, since using VPU wrapper need too much work for me, but libimxvpuapi need much less work, so I would like to say good job.

**Comment by dv1** [comment]
Thanks! I'll add Annex.B byte-stream as a requirement for the h.264 decoder.
