### ISSUE TITLE
DQT order

### ISSUE THREAD

**Issue by toffe** [Freescale/libimxvpuapi#14]
Hi,

The imxvpulib inputs the DQT tables in "natural order" into the imx-vpu library, which emits them in the same order into the DQT marker of the JPEG header. The DQT should be in zig zag order though according to the JPEG spec.

It is not clear to me if the VPU expects another order? There is a table (table 4) with a slightly permuted ordering of a Q Matrix in the VPU API RM. However the imx-vpu lib writes the DQT marker exactly as it is input into the library by imxvpulib.

**Comment by dv1** [comment]
This part is indeed confusing. I generally followed what libfslvpuwrap was doing, and then replaced its strange tables with the the default jpeglib ones.

I do find the "natural" order to be much more intuitive. However, it is not standards compliant. To not break compatibility, I'll keep it as it is, and add a note that the library inputs the tables in "natural" order.

**Comment by toffe** [comment]
I'm trying to get an answer from NXP here: https://community.nxp.com/thread/429103

JPEG decoders will assume that the DQT is in zig zag order so they will multiply with the incorrect quantization coeffiecient now unfortunately.
