### ISSUE TITLE
Encode 8 bit greyscale JPEG

### ISSUE THREAD

**Issue by lemarquois** [Freescale/libimxvpuapi#15]
Hi,

I'm trying to encode a JPEG image from a raw 8 bit greyscale image.
I took jpeg-enc-example.c as an example and tried with pixel format IMX_VPU_COLOR_FORMAT_YUV400, but did not succeed.
In the attachments you will find my code+Makefile img.raw is the raw input file with a resolution of 1280*964 (8 bits per pixel). I also attached a png version of that image (input.png). My code creates an output file (out.jpeg), which should be the JPEG compressed raw input image.
I tested my code on a seco SBC-A62-J-QUAD with this linux: https://github.com/UDOOboard/linux_kernel/tree/imx_3.14.28_1.0.0_ga_a62

I run my program with ./main -i img.raw -o out.jpeg -q 90

I think I have to change some of the encodings parameters, but did not succeed, can anyone help?

Regards

[data.zip](https://github.com/Freescale/libimxvpuapi/files/370978/data.zip)

**Comment by dv1** [comment]
Weird. I ran tests the other day with greyscale JPEGs and it worked. I'll test with your data.

**Comment by dv1** [comment]
Got it. Color format was passed on when using the regular interface, but not when using the simplified JPEG one. Fixed in latest commit.

**Comment by lemarquois** [comment]
Okay, I just tested your changes, it is working as expected now.
