### ISSUE TITLE
vpu_wrapper can't be found on i.mx6 Quad/DualLite

### ISSUE THREAD

**Issue by lrtxpra** [Freescale/libimxvpuapi#24]
I use this API on i.mx6 Quad/DualLite, but there is a problem that vpu_wrapper.h can't be found.
Then I found a vpu_wrapper on github, https://github.com/finallyshen/freescale_omx_framework/tree/master/OpenMAXIL/src/component/vpu_wrapper
but still has several problem, some enum variables has not been defined,
so i doubt that whether i.mx6 Quad/DualLite can use this API

**Comment by dv1** [comment]
Closing this due to the recommendation to not use the fslwrapper backend anymore, and since starting with version 2.0.0, the wrapper backend anyway isn't there anymore.
