### ISSUE TITLE
libimxvpuapi-0.10.3 waf configure fails

### ISSUE THREAD

**Issue by BorisDuch** [Freescale/libimxvpuapi#25]
Hi all,

I am facing an issue when trying to install libimxvpuapi 0.10.3.
./waf configure fails with the following message:
_using the vpulib backend
Checking for library vpu  : not found_

My configuration is as follows:
imx6 platform
GStreamer 1.4.4
libimxvpuapi.so.0.10.2 installed under /usr/lib
libvpu.so.4 installed under /usr/lib

Thanks in advance for your help!

Boris

**Comment by dv1** [comment]
Development is now focused on libimxvpuapi 2. This seems more like an installation error. Look at build/config.log to see more about why the vpu library wasn't found.

Since this is very old, I'm closing it. Feel free to reopen if this issue is still present in libimxvpuapi 2.
