### ISSUE TITLE
imxvpuenc_h264 not working with apple homekit

### ISSUE THREAD

**Issue by angelobt** [Freescale/libimxvpuapi#26]
Hi,
we are implementing an Apple homekit accessory using an imx6solo CPU.

The environment is:
- yocto rocko
- kernel 4.9.11
- latest version of gstreamer1.0-plugins-imx
- latest version of libimxvpuapi

the pipeline is

imxv4l2videosrc -> imxipuvideotransform (deinterlace + resize) -> imxvpuenc_h264 -> appsink

then buffers coming from appsink are sent to apple API that do RTP packetization and UDP transmission.
 
The problem is that apple devices can't start video decoding.

We have tried to use fsl plugins instead of imx ones (vpuenc instead of imxvpuenc_h264) and in this case the video decoding (apple side) works well.

We have seen that inside your library there is a comment about  SPS, PPS, AUD order that 
is no longer guaranteed. Do you think  the problem could be related to that frames order? (commit 17f1328)

Thanks in advance,
Angelo

**Comment by angolini** [comment]
Could you, please, test using the latest version and update the status  @angelobt
