### ISSUE TITLE
Streaming h.264 to chrome with hardware acceleration enabled

### ISSUE THREAD

**Issue by chrisw957** [Freescale/libimxvpuapi#27]
I'm streaming h.264 video from an i.mx6 device (libimxvpuapi 0.10.3) to a chrome browser using gstreamer and  webrtc with the Janus server.    The problem is the browser receives the stream, but never displays it and never shows an error.  If you wait long enough (10 to 15 minutes), it will sometimes eventually start displaying the video.

The chrome browser has hardware acceleration for h.264 enabled.  If I disable it, the issue goes away.  Streaming to firefox doesn't show this issue.  If I use x264enc instead of imxvpuenc_h264, the issue does not appear.  If I force the build to use libimxvpuapi 0.10.1, the issue does not appear, so it is something to do with changes between 0.10.1 and 0.10.3 (probably something to do with NAL order?)

Here is an example pipeline:
<pre>
gst-launch-1.0 -v \                                                             
videotestsrc pattern=ball is-live=true ! \                                      
"video/x-raw,format=(string)I420,width=640,height=480,framerate=(fraction)30/1" 
! \                                                                             
queue ! \                                                                       
imxvpuenc_h264 gop-size=16 bitrate=2000 idr-interval=4 ! \                      
queue ! \                                                                       
rtph264pay pt=126 ! \                                                           
udpsink host=18.221.129.71 port=5012  
</pre>

I tried to do some basic decoding of the stream to see if I could spot something.  I don't claim to understand what is going on here, but here is what I have.

This is when using 0.10.1 and gstreamer 1.6.0.  It doesn't show the problem:
<pre>
GOOD:
Gstreamer 1.6.0
libimxvpuapi.so.0 -> libimxvpuapi.so.0.10.1
0:00:00.116199828  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 7 SPS, size 9
0:00:00.116239578  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 8 PPS, size 4
0:00:00.117765114  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 7 SPS, size 9
0:00:00.117816927  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 8 PPS, size 4
0:00:00.117840804  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.117856934  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 5 Slice IDR, size 1426
0:00:00.149773123  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.149808743  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 293
0:00:00.183538995  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.183610212  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 355
0:00:00.216644445  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.216715732  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 337
0:00:00.251115148  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.251184826  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 5 Slice IDR, size 1339
0:00:00.283100730  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.283168455  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 216
0:00:00.316646349  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.316746349  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 326
0:00:00.349894701  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.349966095  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 349
0:00:00.385143095  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.385219651  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 5 Slice IDR, size 1413
0:00:00.416633423  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.416703636  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 316
0:00:00.449966430  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.450038815  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 397
0:00:00.483213023  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.483281661  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 323
0:00:00.517834024  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.517902363  3514      0x1c24cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 5 Slice IDR, size 1333
</pre>

This is with libimxvpuapi 0.10.3 and gstreamer 1.12.2, and does show the problem:
<pre>
BAD:
Gstreamer 1.12.2
libimxvpuapi.so.0 -> libimxvpuapi.so.0.10.3
:00:00.414378024  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 7 SPS, size 9
0:00:00.414487739  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 8 PPS, size 4
0:00:00.415277119  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 7 SPS, size 9
0:00:00.415425703  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 8 PPS, size 4
0:00:00.415544918  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 1339
0:00:00.447897240  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.447925047  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 186
0:00:00.481285354  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.481361119  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 322
0:00:00.514751481  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.514822577  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 339
0:00:00.547982970  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.548083973  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 363
0:00:00.581302708  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.581373697  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 342
0:00:00.614581666  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
0:00:00.614609918  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 215
0:00:00.647903717  4035      0x1934cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 9 AU delimiter, size 2
</pre>

This is also good (no issue).  It is generated by x264enc:
<pre>
0:00:00.581734237  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 7 SPS, size 24
0:00:00.581781932  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 8 PPS, size 4
0:00:00.582142479  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 7 SPS, size 24
0:00:00.582176517  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 8 PPS, size 4
0:00:00.582203117  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 5 Slice IDR, size 3232
0:00:00.582246699  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 5 Slice IDR, size 731
0:00:00.582276757  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 5 Slice IDR, size 263
0:00:00.582306035  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 5 Slice IDR, size 1303
0:00:00.614860845  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 802
0:00:00.614913653  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 330
0:00:00.614943660  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 9
0:00:00.614972741  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 38
0:00:00.648169119  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 826
0:00:00.648225740  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 417
0:00:00.648255357  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 9
0:00:00.648284177  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 9
0:00:00.681535114  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 720
0:00:00.681600223  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 567
0:00:00.681631064  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 9
0:00:00.681663329  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 9
0:00:00.714865743  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 480
0:00:00.714930914  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 595
0:00:00.714959784  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 9
0:00:00.714988936  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 9
0:00:00.748219173  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 546
0:00:00.748273325  7161       0xaf0cf0 DEBUG              h264parse gsth264parse.c:716:gst_h264_parse_process_nal:<h264parse0> processing nal of type 1 Slice, size 654
</pre>

If you need more information, or access to the janus server sending these streams, I can help.

**Comment by angolini** [comment]
Could you, please, test using the latest version and update the status @chrisw957 ?
