### ISSUE TITLE
VPU MJPEG encode timeout and memory allocation error

### ISSUE THREAD

**Issue by Pehoh** [Freescale/libimxvpuapi#28]
Hello,
I'm using the libimxvpuapi library to encode in JPEG a 13MPix image. I'm facing some issues:
* The iMX6 run out of memory (not everytime), I increased the CMA to 512MB, but I still have allocation errors. Even if I use the __GFP_NOFAIL flag on the kernel for dma_alloc_coherent, I still have allocation errors.
* Trying to understand the memory allocation, I found that the lib allocates a lot of framebuffers for only 1 picture encoding. I don't understand why. On my 13Mpx image, the first allocation is 26MB (YUV422), after that I have 3*32MB of memory allocated
* Also, using a pure random frame, make the encoder crash if the JPEG quality is above 90..

Do you have any idea/ way to improve this?

**Comment by dv1** [comment]
If you can, please provide frames that triggered these issues. I am trying to fix old issues as much as possible now that I have a little bit more time for development.

**Comment by angolini** [comment]
It looks like no update in more than 1 year. I'm closing this issue, but anyone can reopen if needed.
