### ISSUE TITLE
frame / field mode 

### ISSUE THREAD

**Issue by fictionjs** [Freescale/libimxvpuapi#29]
Hello, 

We have a problem with decoding interlaced streams, which were encoded in "field mode"
(with PAFF/MBAFF coding, although it is supported by IMX). VPU cannot properly handle that kind of frames, it works only for a while, then it stops. Everything is fine when we decode streams in "frame mode".
Our platform is based on imx6qp. 
We are using: 
gst1-imx-0.13.0
libimxvpuapi-0.10.3

Can you help us?

**Comment by dv1** [comment]
Looking at old issues now, sorry for not reacting. This is difficult to fix. I need an example h264 stream that triggers this problem.
Note though that I am focusing on fixing things in version 2 of libimxvpuapi due to lack of time.
