### ISSUE TITLE
Unnecessary mandatory flag --imx-headers

### ISSUE THREAD

**Issue by telelaci** [Freescale/libimxvpuapi#31]
In the branch v2 the above parameter is mandatory, you MUST set the path where the linux/mxcfb.h can be found, otherwise the compilation terminates with error.

There is no such source or include file in the whole repository what uses mxcfb.h
The word mxcfb.h can be found in two files only:
README.md
wscript

I think that flag should be removed, it just makes chaos.

**Comment by dv1** [comment]
Fixed the --imx-headers handling. It is not only needed for i.MX6. Can you check if it works for you?

**Comment by dv1** [comment]
Commit e868fc74b5d6659175def5bb50ea71ec225e3ad9 addresses this issue. Closing. Reopen in case problems remain.
