### ISSUE TITLE
Floating Point exception when Using Jpeg_Decode_example

### ISSUE THREAD

**Issue by Geko1990** [Freescale/libimxvpuapi#33]
Hello,

I Tried to use your jpeg decoding example on our ixora imx6 board and it works with some jpegs just fine. But some of our jpegs wont work and the test application throws a floating point exception when it should be decoding. I dont really know if its the filesize or something else, but with jpegs < 2MB it seemed to work just fine.

Here the jpeg it didnt work with:

https://we.tl/t-Zakc2uehDK

Right now all of the image decoding work is done by the software... but doing it with the vpu could give us a pretty good boost of performance so we wanted to try it out. Just to be sure, the jpeg i sent you should work shoudn't it?

greetings Georg

**Comment by dv1** [comment]
Sorry for not reacting. Can you provide the test file again? The link is not valid anymore?

**Comment by angolini** [comment]
It looks like no update in more than 1 year. I'm closing this issue, but anyone can reopen if needed.
