### ISSUE TITLE
JPEG decoder return decode info with null dma buffer

### ISSUE THREAD

**Issue by hoangvanhai** [Freescale/libimxvpuapi#34]
Hello,
I'm using usb camera, capture data format MJPEG and push to imx8m JPEG decoder, When i call `imx_vpu_api_jpeg_dec_decode`, in second time, crash when dma buffer can not map to,  could you finger me the reason of the error:
> ../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:497 (imx_vpu_api_get_free_frame_entry_index)   debug: (re)allocated space for additional frame entry
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1682 (imx_vpu_api_dec_push_encoded_frame)   log: pushed frame with context 0x4059000000000000 PTS 0 DTS 4606281698874543309 frame entry index 0 and 53256 bytes of main data
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1737 (imx_vpu_api_dec_decode)   log: decoding frame(s); drain mode enabled: 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1831 (imx_vpu_api_dec_decode)   debug: VPU has no decoded frames to output
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1878 (imx_vpu_api_dec_decode)   log: scanning for frames in the stream buffer; read offset 0 write offset 53256 fill level 53256
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1894 (imx_vpu_api_dec_decode)   log: found frame, offsets:  first 0  last 53256  associated frame entry index: 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1907 (imx_vpu_api_dec_decode)   log: decode() result:  codec state CODEC_HAS_INFO (2)  num used input bytes 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1878 (imx_vpu_api_dec_decode)   log: scanning for frames in the stream buffer; read offset 0 write offset 53256 fill level 53256
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1894 (imx_vpu_api_dec_decode)   log: found frame, offsets:  first 0  last 53256  associated frame entry index: 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1907 (imx_vpu_api_dec_decode)   log: decode() result:  codec state CODEC_WAITING_FRAME_BUFFER (6)  num used input bytes 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:560 (imx_vpu_api_dec_clear_added_framebuffers)   log: clearing 0 added framebuffer(s)
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:692 (imx_vpu_api_dec_get_new_stream_info)   debug: setnoreorder() called;  frame reordering: 0  codec state: CODEC_ERROR_UNSPECIFIED (-5)
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:727 (imx_vpu_api_dec_get_new_stream_info)   debug: crop rectangle not available, setting whole frame as rectangle instead: left 0 top 0 width 1280 height 720
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:827 (imx_vpu_api_dec_get_new_stream_info)   debug: stream info:  aligned width/height: 1280/720  actual width/height: 1280/720  Y/UV stride: 1280/1280  Y/UV size: 921600/460800  Y/U/V offsets: 0/921600/1382400  sliceheight: 720  min fb pool framebuffer size: 1382400  frame rate: 0/0  min num required framebuffers: 1  color format: semi planar YUV 4:2:0 8-bit  semi-planar: 1  is interlaced: 0  is 10 bit: 0  has HDR metadata: 0  has color description: 0  has location of chroma info: 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:2011 (imx_vpu_api_dec_decode)   log: new stream info was seen earlier, and new framebuffers are needed
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:547 (imx_vpu_api_dec_add_framebuffer_entries)   debug: (re)allocated space for additional 1 framebuffer entries
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1514 (imx_vpu_api_dec_add_framebuffers_to_pool)   debug: adding framebuffer entry with index 0:  virtual address 0xffff4fb28000  physical address 0x55c00000  size 1382400
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1737 (imx_vpu_api_dec_decode)   log: decoding frame(s); drain mode enabled: 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1831 (imx_vpu_api_dec_decode)   debug: VPU has no decoded frames to output
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1878 (imx_vpu_api_dec_decode)   log: scanning for frames in the stream buffer; read offset 0 write offset 53256 fill level 53256
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1894 (imx_vpu_api_dec_decode)   log: found frame, offsets:  first 0  last 53256  associated frame entry index: 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1907 (imx_vpu_api_dec_decode)   log: decode() result:  codec state CODEC_HAS_FRAME (1)  num used input bytes 53256
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1979 (imx_vpu_api_dec_decode)   log: decoded frame is available
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1737 (imx_vpu_api_dec_decode)   log: decoding frame(s); drain mode enabled: 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1774 (imx_vpu_api_dec_decode)   log: found frame entry at index 0 and framebuffer entry at index 0 for decoded frame with physical address 0x55c00000
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:2106 (imx_vpu_api_dec_get_decoded_frame)   log: got frame with context 0x4059000000000000 PTS 0 DTS 4606281698874543309 frame entry index 0 framebuffer entry index 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1737 (imx_vpu_api_dec_decode)   log: decoding frame(s); drain mode enabled: 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1831 (imx_vpu_api_dec_decode)   debug: VPU has no decoded frames to output
[04:40:03:121][Warning]Core:phone.service: buffer got ok
[04:40:03:122][Info]Core:phone.service: hw mjpeg dec_process elapsed = 22.067282 ms
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1682 (imx_vpu_api_dec_push_encoded_frame)   log: pushed frame with context 0xccf8 PTS 11318158608 DTS 281472648902528 frame entry index 0 and 52472 bytes of main data
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1737 (imx_vpu_api_dec_decode)   log: decoding frame(s); drain mode enabled: 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1831 (imx_vpu_api_dec_decode)   debug: VPU has no decoded frames to output
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1878 (imx_vpu_api_dec_decode)   log: scanning for frames in the stream buffer; read offset 0 write offset 52472 fill level 52472
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1894 (imx_vpu_api_dec_decode)   log: found frame, offsets:  first 0  last 52472  associated frame entry index: 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1907 (imx_vpu_api_dec_decode)   log: decode() result:  codec state CODEC_NEED_MORE (0)  num used input bytes 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1878 (imx_vpu_api_dec_decode)   log: scanning for frames in the stream buffer; read offset 0 write offset 52472 fill level 52472
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1894 (imx_vpu_api_dec_decode)   log: found frame, offsets:  first 0  last 52472  associated frame entry index: 0
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1907 (imx_vpu_api_dec_decode)   log: decode() result:  codec state CODEC_HAS_FRAME (1)  num used input bytes 52472
../imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c:1979 (imx_vpu_api_dec_decode)   log: decoded frame is available
phone.service: ../imxdmabuffer/imxdmabuffer.c:81: imx_dma_buffer_map: Assertion `buffer != NULL' failed.
Aborted (core dumped)

**Comment by dv1** [comment]
Hi. Just saw this. Any updates? Did you find out what it was? To me, it seems like you tried to decode a JPEG that the Hantro decoder cannot handle.

**Comment by hoangvanhai** [comment]
Hi dv1, i tried decode the jpeg image continuous jpeg images: the piece of code are:
`s->dec_info = imx_vpu_api_jpeg_dec_decode(s->hw_decoder, frame->b_rptr, data_size);
if(s->dec_info != NULL) {
	 if(s->dec_info->fb_dma_buffer != NULL) {
		mapped_virtual_address = imx_dma_buffer_map(s->dec_info->fb_dma_buffer,
				IMX_DMA_BUFFER_MAPPING_FLAG_READ, &err);
		if (mapped_virtual_address == NULL) {
			ms_error("could not map decoded frame DMA buffer: %s (%d)\n", strerror(err), err);
		} else {
			ms_error("jpeg decode successed\n");
		}
		imx_dma_buffer_unmap(s->dec_info->fb_dma_buffer);
	} else {
		ms_warning("dec_info not null but dec_info->fb_dma_buffer = %p", s->dec_info->fb_dma_buffer);
	}
} else {
	ms_warning("hwmjpeg dec_info error size = %d", data_size);
	ms_filter_notify_no_arg(f,MS_VIDEO_DECODER_DECODING_ERRORS);
}`


when odd time (1, 3, 5 ...), it seems decode properly done, i see output is `jpeg decode successed`, on even time(2, 4, 6 ...) the output is `dec_info not null but dec_info->fb_dma_buffer` means the dma buffer is not filled data.

Could you show me it is missing on my own ?

**Comment by dv1** [comment]
Hi. I am trying to finally clean up old issues. This is one of them. If possible, can you provide a JPEG that triggers this?

**Comment by angolini** [comment]
No update in more than 1 year. I'm closing this issue. If anything else is needed, you can reopen it.
