### ISSUE TITLE
Debian Hantro Library missing

### ISSUE THREAD

**Issue by berkutta** [Freescale/libimxvpuapi#42]
I'm getting `Checking for library hantro              : not found ` when doing `./waf configure --prefix=/usr --sysroot-path=/ --imx-platform=imx8mm`. I also read in the README that I need imx-vpu-hantro 1.8.0 or newer. Where do I get this and how can I build/install it on Debian?

**Comment by dv1** [comment]
I could not find a Debian mirrror with this either. However, you can get it from NXP itself and assemble the link out of meta-freescale. Look up the IMX_MIRROR variable in https://github.com/Freescale/meta-freescale/blob/master/conf/layer.conf and the SRC_URI variable in https://github.com/Freescale/meta-freescale/blob/master/recipes-bsp/imx-vpu-hantro/imx-vpu-hantro_1.20.0.bb .
