### ISSUE TITLE
decoder issue: could not update bitstream buffer with new data: invalid parameters

### ISSUE THREAD

**Issue by garygumdrops** [Freescale/libimxvpuapi#43]
Hi

I am using v1 of the imxvpuapi lib (version 0.10.3) and have noticed the following errors with gstreamer (the imxvpudec) plugin:

0:00:33.109527337  6702  0x1d06460 ERROR              imxvpuapi imxvpuapi_vpulib.c:1744:imx_vpu_dec_push_input_data: could not update bitstream buffer with new data: invalid parameters
0:00:33.109684337  6702  0x1d06460 ERROR          imxvpudecoder decoder.c:603:gst_imx_vpu_decoder_handle_frame:<video_decoder> failed to decode: invalid params
gst_video: Error (h.264 dec): 1(Operation not permitted), src:video_dec_source, message=Internal data stream error.
gst_video: Debug: ../../../../gstreamer-1.14.4/libs/gst/base/gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:video-decoder-pipeline/GstAppSrc:video_dec_source:
streaming stopped, reason error (-5).
gst_video: Error (h.264 dec): 1(Operation not permitted), src:video_dec_queue, message=Internal data stream error.
gst_video: Debug: ../../../gstreamer-1.14.4/plugins/elements/gstqueue.c(988): gst_queue_handle_sink_event (): /GstPipeline:video-decoder-pipeline/GstQueue:video_dec_queue:
streaming stopped, reason error (-5).

It doesn't always happen but does **always** with a video call from a specific SIP client.

Is it the same issue as [this ](https://github.com/Freescale/libimxvpuapi/pull/32)one?

If so, presumably I will need to build the **v1** branch?

Thanks.

Gary

**Comment by dv1** [comment]
Due to lack of resources, I cannot support both v1 and v2. Is there any reason why you use v1?

**Comment by garygumdrops** [comment]
I don't think there is support in yocto for v2 at the moment? Well I guess I mean gstreamer hasn't been updated to support v2.

It's been a while since I worked on this so I guess I just used a software decoder for the time being.

**Comment by dv1** [comment]
libimxvpuapi v2 is already in Yocto. gstreamer-imx v2 is being prepared for a release right now. A Yocto recipe is imminent and scheduled to be included in the next Yocto release in meta-freescale. Watch the meta-freescale repo over the next few days.

**Comment by garygumdrops** [comment]
hi. OK that's great news, I shall keep an eye on new yocto recipe thanks.

I haven't worked on this project for a few months, so once gstreamer-imx v2
appears, it will be a good opportunity to update everything and get back to
it.

**Comment by dv1** [comment]
Alright. gstreamer-imx has been out for about a week by now. If you can try again, and you still see issues, feel free to reopen this issue.
