### ISSUE TITLE
YUYV format on IMX6

### ISSUE THREAD

**Issue by kevlhop** [Freescale/libimxvpuapi#44]
Hi,
I'm actually working on adding libimxvpuapi version 2 to ffmpeg. I'm able to put on the network an encoded camera stream from a IMX6 platform.
Unfortunately, I have an issue concerning the format available in the library for imx6. My camera is streaming in a YUYV422 format and I saw that you have added this format to the library but only for IMX8 platforms. Do you know if I can replace the YUYV format by one supported by IMX6? And which one ? Or is it not possible for IMX6 to encode a YUYV format ?
Thank you,
Kévin

**Comment by LanderN** [comment]
@kevlhop did you succeed in adding libimxvpuapi codecs to ffmpeg? Is the code open source?

**Comment by kevlhop** [comment]
Hi @LanderN,
I have succeeded to have something working in ffmpeg. They are clearly optimisation and rework to do, to have better performances (like removing some memory copies or put the codec in hardware codecs instead of software codecs maybe). Yes, the code is available here: https://github.com/savoirfairelinux/FFmpeg/tree/sfl/master
If you have any comments or working on an improvement, I would love to see that :)
