### ISSUE TITLE
imxvpuapi2_imx8_amphion: error decode MJPEG stream

### ISSUE THREAD

**Issue by tiny69712** [Freescale/libimxvpuapi#57]
Hello,
I'm currently using this lib for decoding a MJPEG stream from camera.
It seems that the library for the amphion decoder does not initialize the frame height and frame width, which causes a driver error when requesting a buffer:
```
[VPU Decoder] reqbuf->count = 2
[VPU Decoder] sizeimage isn't initialized, OUTPUT reqbufs failed
```
This does not affect the H264 stream because that information is already included.

Test on Toradex Apalis iMX8QM board, with linux kernel 5.4.

**Comment by dv1** [comment]
The `imxvpuapi2_imx8_amphion` branch is not meant for general use; it was for a specific use case, and is now deprecated, since gstreamer-imx has a dedicated decoder element for the Amphion VPU. Please try using that.
