### ISSUE TITLE
YUYV format

### ISSUE THREAD

**Issue by alexisImajing** [Freescale/libimxvpuapi#6]
Hi, 

Is it possible to encode a raw picture of format YUYV422 with the libimxvpuapi? (as V4L2-PIX-FMT-YUYV)

Thanks,
Alexis

**Comment by dv1** [comment]
Only if JPEG is used as the encoding format. The others only support 4:2:0 (either as I420 or as NV12, depending on whether chroma interleave is 0 or 1).

**Comment by dv1** [comment]
Please consider using the IPU, PxP or G2D cores to convert the colorspace. Closing issue.
